### ISSUE TITLE
This is not Pure Java

### ISSUE THREAD

**Issue by keinhaar** [DenisLAD/twain4java#1]
A Pure Java implementation would not require jna or any DLL like this one does.
So it's not Pure JAVA.
There's no hint, that jna is required and no hint where to get the TWAIN_32.dll.
Could you explain where i could get the library.

**Comment by DenisLAD** [comment]
TWAIN_32/TWAIN_64/TWAINDSM is a part of default scanning drivers from manufactuers.
Or you can try to use virtual driver from [SourceForge](https://sourceforge.net/projects/twain-samples/files/TWAIN%202%20Sample%20Data%20Source/TWAIN%20DS%202.1.3/)
